# Generated by Django 6.1.1 on 2026-09-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_blood_group_patient_email_patient_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
