# Generated by Django 6.1.1 on 2026-09-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_role_role_name_dept_is_active_and_more'),
        ('api', '0004_patient_gender'),
    ]

    operations = [
    ]
