# Generated by Django 6.1.1 on 2026-09-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20260911_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
