# Generated by Django 6.1.1 on 2026-09-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20260911_1633'),
        ('api', '0006_rename_name_role_role_name'),
    ]

    operations = [
    ]
