# Generated by Django 6.1.1 on 2026-09-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20260913_1202'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDispenseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Medicine dispense',
                'verbose_name_plural': 'Medicine dispenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pharmacy.medicinedispense',),
        ),
    ]
