# Generated by Django 6.1.1 on 2026-09-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_medicinedispenseproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='dept',
        ),
    ]
