# Generated by Django 6.1.1 on 2026-09-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_medicinedispenseproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.laborder')),
            ],
        ),
    ]
